title:        'Marcus Ellis'
tagline:      'Marcus Ellis &middot; Front End Web Developer'
description:  'Front End Web Developer'
url:          http://marcusellis05.github.io
author:
  name:       'Marcus Ellis'
  username:   'marcusellis05'
  email:      'marcusellis05@gmail.com'
markdown:     redcarpet
permalink:    pretty
pygments:     true
lsi:          true
paginate:     5
excerpt_separator: <!--more-->
