title:        'Marcus Ellis'
tagline:      'Marcus Ellis | Front End Web Developer'
description:  'Front End Web Developer'
url:          http://marcusellis05.github.io
author:
  name:       'Marcus Ellis'
  email:      'marcusellis05@gmail.com'
permalink:    pretty
pygments:     true
paginate:     5
